const questions = {
  1 : "http://blendingbingo.s3-us-west-1.amazonaws.com/top.mp3",
  2 : "http://blendingbingo.s3-us-west-1.amazonaws.com/ten.mp3",
  3 : "http://blendingbingo.s3-us-west-1.amazonaws.com/pot.mp3",
  4 : "http://blendingbingo.s3-us-west-1.amazonaws.com/pin.mp3",
  5 : "http://blendingbingo.s3-us-west-1.amazonaws.com/pig.mp3",
  6 : "http://blendingbingo.s3-us-west-1.amazonaws.com/pen.mp3",
  7 : "http://blendingbingo.s3-us-west-1.amazonaws.com/pan.mp3",
  8 : "http://blendingbingo.s3-us-west-1.amazonaws.com/kiss.mp3",
  9 : "http://blendingbingo.s3-us-west-1.amazonaws.com/jet.mp3",
  10 : "http://blendingbingo.s3-us-west-1.amazonaws.com/jam.mp3",
  11 : "http://blendingbingo.s3-us-west-1.amazonaws.com/gum.mp3",
  12 : "http://blendingbingo.s3-us-west-1.amazonaws.com/doll.mp3",
  13 : "http://blendingbingo.s3-us-west-1.amazonaws.com/dog.mp3",
  14 : "http://blendingbingo.s3-us-west-1.amazonaws.com/dad.mp3",
  15 : "http://blendingbingo.s3-us-west-1.amazonaws.com/cat.mp3",
  16 : "http://blendingbingo.s3-us-west-1.amazonaws.com/can.mp3",
  17 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bus.mp3",
  18 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bun.mp3",
  19 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bug.mp3",
  20 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bib.mp3",
  21 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bell.mp3",
  22 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bed.mp3",
  23 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bag.mp3",
  24 : "http://blendingbingo.s3-us-west-1.amazonaws.com/bag.mp3",
  25 : "http://blendingbingo.s3-us-west-1.amazonaws.com/sub.mp3"
};

module.exports = questions;

// const questions = {
//   1 : "T-O-P",
//   2 : "T-E-N",
//   3 : "P-O-T",
//   4 : "P-I-N",
//   5 : "P-I-G",
//   6 : "P-E-N",
//   7 : "P-A-N",
//   8 : "K-I-S-S",
//   9 : "J-E-T",
//   10 : "J-A-M",
//   11 : "G-U-M",
//   12 : "D-O-L-L",
//   13 : "D-O-G",
//   14 : "D-A-D",
//   15 : "C-A-T",
//   16 : "C-A-N",
//   17 : "B-U-S",
//   18 : "B-U-N",
//   19 : "B-U-G",
//   20 : "B-I-B",
//   21 : "B-E-L-L",
//   22 : "B-E-D",
//   23 : "B-A-T",
//   24 : "B-A-G",
//   25 : "S-U-B"
// };
